# cloudbuild.yamlのサンプル
# https://cloud.google.com/build/docs/deploying-builds/deploy-cloud-run
# cloudbuild.yamlで使える環境変数一覧
# https://cloud.google.com/build/docs/configuring-builds/substitute-variable-values

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
      '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
    '-t',
      '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest',
    '--file',
      './docker/Dockerfile',
    '.'
  ]
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: gcloud
  args: [
    'run',
    'deploy',
      '$_SERVICE_NAME',
    '--image',
      '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
    '--region',
      '$_DEPLOY_REGION'
  ]
timeout: 3600s
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:latest'
options:
  machineType: "E2_HIGHCPU_8"